### ISSUE TITLE
Downloadable .exe does not work because of Single Bundled File

### ISSUE THREAD

**Issue by hubermarkus** [f0rw4rd/knxunlocker#1]
![grafik](https://github.com/f0rw4rd/knxunlocker/assets/3829816/8a18d02d-25e0-45e6-aae9-968724ba4e68)

Solution -> download source code and compile yourself (e.g. Visual Studio 2022)

**Comment by f0rw4rd** [comment]
Thx for the pointer, I will remove the single bundle files because they cause more troubles as they are worth
