### ISSUE TITLE
Snipped for generating a keys.txt file if a part of the key is known 

### ISSUE THREAD

**Issue by hubermarkus** [f0rw4rd/knxunlocker#2]
In the example the 2 middle bytes 1A 57 are known and a file with all combinations (2^16 = 65536) is created.
Note that you should  "also" always test the codes with reversed byte order (little endian / big endian).

In our case, the attacker kindly provided the following hint (but in reverse byte (not reverse bit) order)
![grafik](https://github.com/f0rw4rd/knxunlocker/assets/3829816/b29468c2-0d02-4d52-9964-4a68a8627775)

strangely enough, almost all devices swallowed the reversed byte order only one swallowed the normal one

namespace ConsoleApp2
{
    using System;
    using System.IO;
    using System.Text;

    class Program
    {
        static void Main()
        {
            // Pfad zur CSV-Datei, die erstellt wird
            string filePath = "keys.txt";

            // StringBuilder-Instanz, um die CSV-Daten zu speichern
            StringBuilder csvContent = new StringBuilder();

            // Schleife, die von 0x0000 bis 0xFFFF zählt
            for (int i = 0; i <= 0xFFFF; i++)
            {
                // Formatierung des aktuellen Wertes als Hexadezimalstring
                string hexValue = i.ToString("X4");

                // Hinzufügen der Zeile zum StringBuilder
                // Anpassung: Ersetzen von "xx" durch "vw" und "xy"
                csvContent.AppendLine($"{hexValue.Substring(0, 1)}{hexValue.Substring(1, 1)}1A57{hexValue.Substring(2, 1)}{hexValue.Substring(3, 1)}");
            }

            // Schreiben des StringBuilder-Inhalts in die CSV-Datei
            File.WriteAllText(filePath, csvContent.ToString());

            Console.WriteLine("CSV-Datei wurde erstellt.");
        }
    }
}

**Comment by f0rw4rd** [comment]
Thank you for reporting this and the commit 51df624 added this feature to the unlocker.
